### ISSUE TITLE
Rich text editor toolbar not visible

### ISSUE THREAD

**Issue by AndyVokurka** [skttl/our-umbraco-matryoshka#1]
Hi. Same issue as with Cultiv Tabify:
When using Rich text editor with lots of text inside of grid (so that I have to scroll down) the RTE toolbar gets hidden.

**Comment by AndersBrohus-MySupport** [comment]
I have made some CSS which fixes this and it is in PR #2 :)

**Comment by skttl** [comment]
Seems to work here though?

![yRi0prsIGF](https://user-images.githubusercontent.com/3726467/73882945-5435de00-4863-11ea-8ec3-004aa308636c.gif)

**Comment by skttl** [comment]
Thanks @AndersBrohus-MySupport 

I'm not sure I like this solution though. You still get 64px of invisible toolbar before it repositions.

I think I would rather have the reorder bar not be sticky instead, and then instead of changing the top position of the toolbar, add a margin-top of 8px to push a bit further down and make things look nice.

What do you think?
![image](https://user-images.githubusercontent.com/3726467/73884847-fdca9e80-4866-11ea-88ff-8661589c8b54.png)

**Comment by skttl** [comment]
Just to clarify, I almost never use the RTE in a grid (I use DTGEs for everything), so I have never run into this issue :)

**Comment by AndersBrohus-MySupport** [comment]
Hi again :)

It looks fine to me :)
But in a normal v8 isn't the reorder by sticky there?

If it is, shouldn't it continue to be it then? :)

**Comment by skttl** [comment]
It is, and probably should. I just don't like that the toolbar doesn't attach before scrolling the extra 64px. Maybe it's just me though :)

**Comment by skttl** [comment]
Fixed in #2
